Support metrics for single model mode
openvinotoolkit/operator pull request #72
Opened 2022-12-13 11:14 UTC by mzegla

2022-12-20 08:41 UTC, rasapala requested changes

2022-12-20 08:41 UTC, rasapala commented on bundle/manifests/intel.com_model_servers.yaml
> +                  description: Configuration of service and model monitoring. This works only for single model mode. For serving multiple models, metrcs are enabled via configuration file.
metrics are enabled

2022-12-20 08:41 UTC, rasapala commented on bundle_k8s/manifests/intel.com_model_servers.yaml
> +                  description: Configuration of service and model monitoring. This works only for single model mode. For serving multiple models, metrcs are enabled via configuration file.
metrics are enabled

2022-12-20 08:41 UTC, rasapala commented on config/crd/bases/intel.com_model_servers.yaml
> +                  description: Configuration of service and model monitoring. This works only for single model mode. For serving multiple models, metrcs are enabled via configuration file.
metrics are enabled

2022-12-20 14:50 UTC, rasapala approved these changes
LGTM

2023-01-02 15:05 UTC, mzegla commented on bundle/manifests/openvino-operator.clusterserviceversion.yaml
> +            "image_name": "registry.connect.redhat.com/intel/openvino-model-server:2022.3",
replace with sha

2023-01-02 15:06 UTC, mzegla commented on bundle/manifests/intel.com_model_servers.yaml
> +                  description: Configuration of service and model monitoring. This works only for single model mode. For serving multiple models, metrics are enabled via configuration file.
add link to metrics docs

2023-01-09 11:10 UTC, merged